/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.falkolab.notificationfactory;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;

@Kroll.module(name = "Notificationfactory", id = "com.falkolab.notificationfactory")
public class NotificationfactoryModule extends KrollModule {
	// Standard Debugging variables
	private static final String LCAT = "NotificationfactoryModule";
	// private static final boolean DBG = TiConfig.LOGD;

	public static final String PROPERTY_BIG_TEXT = "bigText";
	public static final String PROPERTY_BIG_CONTENT_TITLE = "bigContentTitle";
	public static final String PROPERTY_SUMMARY_TEXT = "summaryText";
	public static final String PROPERTY_BIG_LARGE_ICON = "bigLargeIcon";
	public static final String PROPERTY_BIG_PICTURE = "bigPicture";

	public NotificationfactoryModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is
		// created
	}

	// Kept for compatibility with 1.5.x
	public NotificationProxy createNotification(Object[] args) {
		Log.d(LCAT, "createNotification");
		NotificationProxy notification = new NotificationProxy();
		notification.handleCreationArgs(this, args);
		return notification;
	}
}
